# encoding: UTF-8

control 'V-00194' do
    title 'The application must provide centralized management and configuration of the content to be captured in audit records generated by all application components.'
    desc  "Without the ability to centrally manage the content captured in the audit records, identification, troubleshooting, and correlation of suspicious behavior would be difficult and could lead to a delayed or incomplete analysis of an ongoing attack.
	This requirement requires that the content captured in audit records be managed from a central location (necessitating automation). Centralized management of audit records and logs provides for efficiency in maintenance and management of records, as well as the backup and archiving of those records. Application components requiring centralized audit log management must have the capability to support centralized management.
	This requirement applies to centralized management applications or similar types of applications designed to manage and configure audit record capture."
    desc  'rationale', ''
    desc  'check', ""
    desc  'fix', ""
    impact 0.5
    tag severity: 'medium'
    tag gtitle: 'SRG-APP-000356'
    tag gid: 'V-00194'
    tag rid: ''
    tag stig_id: 'SRG-APP-000356'
    tag fix_id: ''
    tag cci: ['CCI-001844']
    tag nist: ['AU-3 (2)']

    describe 'This check is Not Applicable.' do
        skip 'Not Applicable: Central Storage is outside the Kubernetes scope.'
    end
end