include: 
    - local: /ci/.lint-stage.yml
    - local: /ci/.check-stage.yml
    - local: /ci/.exec-stage.yml
  
image: docker:19.03.12

variables:  
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_DRIVER: overlay2
  
services:
    - docker:19.03.12-dind
  
stages:
  - build
  - lint 
  - check
  - exec
  
build:
    tags:
        - docker
    stage: build 
    script: 
        - docker login repo.dsolab.io -u admin -p $CI_PW
        - docker run --rm -v $CI_PROJECT_DIR/:/profiles repo.dsolab.io/ci/scancli:1.0 inspec search -t /profiles
  
