# encoding: UTF-8

control 'V-CIS6219' do
  title 'The AUDSYS.AUD$UNIFIED Audit Option Is Enabled'
  desc  "The AUDSYS.AUD$unified HOLDS AUDIT TRAIL RECORDS GENERATED BY THE DATABASE.  ENABLING THIS AUDIT ACTION CAUSES LOGGGING OF ALL ACCESS ATTEMPTS TO THE AUDSYS.AUD$UNIFIED."
  desc  'rationale', ''
  desc  'check', "
    From SQL*Plus:
 WITH  CIS_AUDIT(AUDIT_OPTION) AS ( SELECT * FROM TABLE( DBMSOUTPUT_LINESARRAY( 'AUD$UNIFIED' ) )  ), AUDIT_ENABLED AS  ( SELECT DISTINCT OBJECT_NAME   FROM AUDIT_UNIFIED_POLICIES AUD   WHERE AUD.AUDIT_OPTION IN ('ALL' )        AND AUD.AUDIT_OPTION_TYPE = 'OBJECT ACTION'        AND AUD.OBJECT_SCHEMA = 'AUDSYS'        AND AUD.OBJECT_NAME = 'AUD$UNIFIED'        AND EXISTS (SELECT *                    FROM AUDIT_UNIFIED_ENABLED_POLICIES ENABLED                    WHERE ENABLED.SUCCESS = 'YES'                        AND ENABLED.FAILURE = 'YES'                        AND ENABLED.ENABLED_OPTION = 'BY USER'                        AND ENABLED.ENTITY_NAME = 'ALL USERS'                        AND ENABLED.POLICY_NAME = AUD.POLICY_NAME) ) SELECT C.AUDIT_OPTION  FROM CIS_AUDIT C
	LEFT JOIN AUDIT_ENABLED E ON C.AUDIT_OPTION = E.OBJECT_NAME  WHERE E.OBJECT_NAME  IS NULL;
    "
  desc  'fix', "
      From SQL*Plus:

	ALTER AUDIT POLICY CIS_UNIFIED_AUDIT_POLICY ADD ACTIONS ALL ON AUDSYS.AUD$UNIFIED; 

    The above SQL*Plus command will set the parameter to take effect at next
system startup.
  "
  impact 0.7
  tag severity: 'high'
  tag gtitle: 'SRG-APP-000516-DB-999900'
  tag gid: 'CIS6218'
  tag rid: ''
  tag stig_id: 'N/A'
  tag fix_id: ''
  tag cci: ['']
  tag nist: ['CM-6 b']                                                                                                                                                                                                          
sql = oracledb_session(user: input('user'), password: input('password'), host: input('host'), service: input('service'), sqlplus_bin: input('sqlplus_bin'))

parameter = sql.query("WITH CIS_AUDIT(AUDIT_OPTION) AS (SELECT * FROM TABLE( DBMSOUTPUT_LINESARRAY('AUD$UNIFIED') ) ), AUDIT_ENABLED AS (SELECT DISTINCT OBJECT_NAME FROM AUDIT_UNIFIED_POLICIES AUD WHERE AUD.AUDIT_OPTION IN ('ALL') AND AUD.AUDIT_OPTION_TYPE = 'OBJECT ACTION' AND AUD.OBJECT_SCHEMA = 'AUDSYS' AND AUD.OBJECT_NAME = 'AUD$UNIFIED' AND EXISTS (SELECT * FROM AUDIT_UNIFIED_ENABLED_POLICIES ENABLED WHERE ENABLED.SUCCESS = 'YES' AND ENABLED.FAILURE = 'YES' AND ENABLED.ENABLED_OPTION = 'BY USER' AND ENABLED.ENTITY_NAME = 'ALL USERS' AND ENABLED.POLICY_NAME = AUD.POLICY_NAME) ) SELECT C.AUDIT_OPTION FROM CIS_AUDIT C LEFT JOIN AUDIT_ENABLED E ON C.AUDIT_OPTION = E.OBJECT_NAME WHERE E.OBJECT_NAME IS NULL;").column('audit_option') 

describe 'AUDUNI' do
subject { parameter }
it {should be_empty }
end
end

