# encoding: UTF-8

control 'V-00145' do
    title 'The application must invalidate session identifiers upon user logout or other session termination.'
    desc  "Captured sessions can be reused in \"replay\" attacks. This requirement limits the ability of adversaries from capturing and continuing to employ previously valid session IDs.
	This requirement focuses on communications protection for the application session rather than for the network packet. This requirement applies to applications that utilize communications sessions. This includes, but is not limited to, web-based applications and Service-Oriented Architectures (SOA). 
	Session IDs are tokens generated by web applications to uniquely identify an application user's session. Applications will make application decisions and execute business logic based on the session ID. Unique session identifiers or IDs are the opposite of sequentially generated session IDs which can be easily guessed by an attacker. Unique session IDs help to reduce predictability of said identifiers. When a user logs out, or when any other session termination event occurs, the application must terminate the user session to minimize the potential for an attacker to hijack that particular user session."
    desc  'rationale', ''
    desc  'check', ""
    desc  'fix', ""
    impact 0.5
    tag severity: 'medium'
    tag gtitle: 'SRG-APP-000220'
    tag gid: 'V-00145'
    tag rid: ''
    tag stig_id: 'SRG-APP-000220'
    tag fix_id: ''
    tag cci: ['CCI-001185']
    tag nist: ['SC-23 (1)']

    describe 'This check is Not Applicable.' do
        skip 'Not Applicable: Network management falls outside the scope of Kubernetes scope.'
    end
end